@startuml
Class Incidente {
-String id;
-Cliente cliente;
-List <Problema> problemaReportado;
-SistemaOperativo os;
-List<Tecnico> tecnicos;
-Time tiempoMaximoResolucion;
-Timestamp fechaInicio;
+Estado estado;

}

@enduml